ummgoban/client-app

babel.config.js, package.json, tsconfig.json, yarn.lock
- alias import 적용합니다.
- `@types`의 경우 typescript org이름이라서 `@/types`로 import 해야합니다.
=> chore: setting alias import

.eslintrc.js, src/apis/Market.ts, src/apis/Order.ts, src/components/myPage/OrderHistory.tsx, src/components/orderPage/PaymentSummary.style.tsx, src/components/orderPage/PaymentSummary.tsx, src/navigation/RegisterNavigator.tsx, src/screens/FeedScreen/SearchBar.style.tsx, src/screens/MyPageScreen/UserMyPage.tsx, src/screens/MyPageScreen/index.tsx, src/screens/RegisterScreen/LoginScreen.tsx, src/screens/RegisterScreen/SignupScreen.tsx, src/types/Market.ts, src/types/OrderType.ts
resolves: #25 
- MarketType, OrderType 수정합니다. ( cc. @itslitulinchpin2 )
- 결제 내역 카드 컴포넌트 제작합니다. 
- 스타일 적용은 최소한으로 진행하였습니다.
=> feat: 결제 내역 카드 컴포넌트 제작합니다.

src/components/feedPage/Market.style.tsx, src/context/EmotionProvider.tsx, src/context/ReactNativePaperProvider.tsx, src/context/emotion.d.ts, src/context/index.tsx, src/context/theme.ts
- `emotion`과 `react-native-paper` 두 라이브러리 모두 적용할 수 있도록 theme 선언합니다.
=> chore: theme can be used in emotion and react-native-paper 

src/apis/Market.ts, src/apis/MarketDetail.ts, src/apis/Order.ts, src/apis/index.ts, src/components/marketDetailPage/MarketImageSlider.style.tsx, src/components/marketDetailPage/MarketImageSlider.tsx, src/components/marketDetailPage/Menu.style.tsx, src/components/marketDetailPage/Menu.tsx, src/components/marketDetailPage/index.ts, src/navigation/DetailNavigator.tsx, src/screens/FeedScreen/index.tsx, src/screens/MarketDetailScreen/MarketDetail.style.tsx, src/screens/MarketDetailScreen/MarketDetailPage.tsx, src/screens/MarketDetailScreen/index.tsx, src/types/Market.ts, src/types/ProductType.ts
resolve: #8 
- 가게 상세 페이지 개발
- 반찬 태그별 슬라이드바, 애니메이션 구현
- useState를 통해 가벼운 장바구니 상태 관리 기능 추가
- `MarketImageSlider` 컴포넌트 개발
```typescript
export type ProductType = {
id: number;
name: string;
image: string;
originalPrice: number;
discountPrice: number;
tags: string[];
};
```
- productType에 tags를 추가합니다. '추천메뉴', '나물류' 등이 포함될 수 있는 문자열 배열입니다.
- 상세 페이지 사이드바 구현에 가장 효과적일 것 같아 추가했고 기존 코드나 더미데이터 충돌이 있으면 해결 필요할 것 같습니다 
- storeType에도 넣어야 할지 고민했는데 아직은 넣지 않았고 추후 논의 필요해 보입니다
- 안드로이드도 정상빌드됩니다
- 디자인은 점진적 개선합니다.
- 가게 상세 페이지에서 어차피 반찬 사진을 map으로 모두 보여줘서 배민과 달리 그냥 가게 이미지 자체를 빼고 싶은데 의견 받습니다.
- 같은 맥락에서 `marketImageSlider`는 구현은 완료했지만 주석 처리 해두었습니다.
- 백엔드 연결되면 fetch부분 완성하고 상태관리 해야할 것 같네요
=> feat: 가게 상세페이지 제작

.github/workflows/lint.yml
- #64 
- #65
- ts, tsx, deps 가 바꿔었을 때만 워크플로우를 시행
- dependabot/ branch의 경우 워크플로우 스킵
=> chore: skip workflow

src/apis/ApiClient.ts, src/apis/Login.ts, src/types/Session.ts
=> fix: rename jwtToken to jwt

src/components/map/MyLocationMap.tsx, src/screens/FeedScreen/index.tsx, src/types/StackNavigationType.ts
- 지도 marketId type 수정: string->number
- 현재 위치 클릭시 네비게이션허용X
=> fix: 지도 params타입/현재 위치 수정 

src/components/feedPage/Market.style.tsx, src/components/feedPage/Market.tsx
=> fix: update market image display and filter hidden products

android/build.gradle, src/components/map/MyLocationMap.tsx, src/screens/FeedScreen/index.tsx
- react-native-geolocation-service 라이브러리를 사용했습니다. (기존 사용한게 너무 오래돼서..)
- 실제 안드로이드 기기에서 실시간 위치 동작 확인 완료
- build.gradle 일부수정 (빌드 잘 될거에요.......)
- 피드페이지에서 하고 있는 권한 허용 세팅들은 추후 전부 초기세팅페이지로 옮겨야 할 것 같네요
=> fix: 실제 모바일 기기에서 현재 위치 받아오기

src/apis/ApiClient.ts, src/apis/Order.ts, src/components/orderPage/DatePickerCard.tsx, src/context/TossPaymentProvider.tsx, src/screens/PaymentScreen/PaymentPage.tsx
=> feat: 결제 연동합니다.

react-native-config.d.ts, src/context/TossPaymentProvider.tsx
=> fix: rn config 적용

src/screens/FeedScreen/index.tsx, src/screens/MarketDetailScreen/MarketDetail.style.tsx, src/screens/SettingScreen/index.tsx, src/utils/notification.ts
resolve:#88
- 위치 권한 세팅 추가 : 토글에 따라 변경
- 위치 허용 하지 않는 경우 디폴트 위치로 가게 열람하도록 로직 수정
=> fix: 위치 권한 세팅 추가

src/components/orderPage/DatePickerCard.style.tsx, src/components/orderPage/DatePickerCard.tsx, src/screens/PaymentScreen/PaymentPage.tsx, src/screens/PaymentScreen/index.tsx
=> feat: pickup date 서버로 받아오기

app.json, src/components/common/DatePicker.tsx, src/screens/PaymentScreen/PaymentPage.tsx, src/utils/date.ts
=> fix: 픽업 시간 오늘 날짜로 수정

src/screens/MarketDetailScreen/MarketDetailPage.tsx
=> fix:첫번째 태그로 디폴트 선택

src/navigation/DetailNavigator.tsx, src/screens/PaymentScreen/PaymentPage.tsx
상민이형하고 의논하면서 결제 로직 떼고 예약으로 변경했습니다.
- 예약으로 변경됨에 따라 클라이언트 앱에서 예약하기 누르는 순간 재고 차감되는 로직으로 정했습니다.
- 사장 앱에서 주문 접수 취소 누르면 재고 복구됩니다.
=> fix: 결제 로직 예약 변경

src/components/marketDetailPage/Menu.tsx
=> fix: 할인가와 정가가 같은 제품 정가만 표시

src/components/marketDetailPage/Menu.style.tsx, src/components/marketDetailPage/Menu.tsx, src/screens/SubscribeScreen/index.tsx
- 찜 리스트 무한렌더링 해결
- 품절 메뉴 표시, disable처리
=> fix: 품절 메뉴 표시 / 찜한 가게 무한렌더링 해결

package.json, src/components/common/CustomImageModal.tsx, src/components/marketDetailPage/Menu.style.tsx, src/components/marketDetailPage/Menu.tsx, yarn.lock
- react-native-image-modal 이용해서 이미지 모달뷰 제작했습니다.
안드로이드 apk 빌드해서 확인했습니다.
렌더링이 부드럽게 되지 않는데.. 폰에서는 좀 낫습니다. 차후 고쳐나가는거로
그래도 없는 것보단 사장님 입장에서 고객 어필 차원에 나을 것 같아서 넣었습니다.
=> feat: 이미지 모달 뷰 라이브러리 이용 제작

src/apis/ApiClient.ts, src/apis/Market.ts, src/components/CartPage/MarketInfo.style.tsx, src/components/CartPage/MarketInfo.tsx, src/components/common/BottomButton.style.tsx, src/components/feedPage/Market.tsx, src/components/marketDetailPage/Menu.style.tsx, src/components/marketDetailPage/Menu.tsx, src/components/orderDetail/OrderDescription.tsx, src/components/orderPage/DatePickerCard.tsx, src/components/subscribePage/SubscribeMarketCard.style.tsx, src/components/subscribePage/SubscribeMarketCard.tsx, src/navigation/MyPageNavigator.tsx, src/screens/MarketDetailScreen/MarketDetailPage.tsx, src/screens/MyPageScreen/NonMemberMyPage.style.tsx, src/screens/MyPageScreen/NonMemberMyPage.tsx, src/screens/MyPageScreen/NoticePage.style.tsx, src/screens/MyPageScreen/NoticePage.tsx, src/screens/MyPageScreen/PolicyPage.tsx, src/screens/MyPageScreen/UserMyPage.tsx, src/screens/OrderDetailScreen/index.tsx, src/screens/PaymentScreen/PaymentPage.style.tsx, src/screens/PaymentScreen/PaymentPage.tsx, src/screens/ShoppingCartScreen/EmptyCartPage.style.tsx, src/screens/ShoppingCartScreen/ShoppingCartPage.style.tsx, src/screens/ShoppingCartScreen/ShoppingCartPage.tsx, src/screens/SubscribeScreen/SubscribeScreen.style.tsx, src/screens/SubscribeScreen/index.tsx, src/types/OrderType.ts, src/types/StackNavigationType.ts
- api 디버그 콘솔 프리티하게 합니다.
| <img width="492" alt="스크린샷 2024-12-12 오후 4 26 50" src="https://github.com/user-attachments/assets/987fa4ed-4c61-4741-ae74-aeba8d7fcea0" /> |
| - |
| 빈 장바구니 | 찜한 가게 | 장바구니 카드 + 바텀 버튼 |
| - | - | - |
| ![Screenshot_1733987870](https://github.com/user-attachments/assets/6edf9040-3a00-48cc-80a8-944365c7e39a) | ![Screenshot_1733987718](https://github.com/user-attachments/assets/5f8dfcfe-8c03-41b4-ac9e-a88f8e8ca46b) | ![Screenshot_1733989337](https://github.com/user-attachments/assets/dd97399e-6934-4c0d-85e7-1e0442c66760) |
| 픽업 예약 남은 시간 | 홈 피드(영업시간 + 픽업 가능 시간) |
| - | - |
| ![Screenshot_1733987019](https://github.com/user-attachments/assets/a4edfb1c-b8e3-4c9d-9e54-3c59c872e39c) | ![Screenshot_1733987016](https://github.com/user-attachments/assets/8b894a40-43b6- …
=> fix: debug 콘솔 pretty, UX 라이팅 및 디자인 수정 

App.tsx, src/utils/notification.ts
- 어드민이랑 fcm 로직 동일하게 맞췄습니다
일단 에뮬레이터상에서 메뉴 추가 알림이 잘 오긴 하는데 더블체크부탁해요~ @l-lyun
=> fix:fcm 로직 어드민과 동일하게 수정

android/app/build.gradle, android/app/src/main/java/com/clientapp/MainActivity.kt, android/app/src/main/java/com/clientapp/MainApplication.kt, package.json, src/apis/Login.ts
=> chore: android aab 빌드합니다.

src/utils/common.ts
=> fix: 로그인 정보 애플 표시

App.tsx, src/apis/Fcm.ts, src/apis/Login.ts, src/screens/FeedScreen/index.tsx, src/screens/SettingScreen/index.tsx, src/utils/notification.ts
피드페이지에서 권한 없을 때 묻는 로직 삭제했습니다.
App.tsx에서 푸시알림 핸들러 실행합니다.
- 차후 실행 필요없어보여 전부 삭제했습니다.
- 로그인에 registerFCMToken 묶었습니다.
- feedPage useIsFocused 적용해서 데이터 fetching하는데 확인 한번만 부탁드릴게요 cc. @itslitulinchpin2
=> fix: fcm logic splash screen

src/apis/Login.ts, src/screens/RegisterScreen/LoginScreen.tsx
#135 (net resolved yet)
- api endpoint 수정사항 반영합니다.
- 일반 회원가입/로그인 함수 추가합니다.
- 선제적 반영을 위하여 기타 필요한 부분은 TODO로 남겨둡니다.
=> feat: ouath와 일반 회원가입 api 인터페이스 설계

App.tsx, ios/ClientApp.xcodeproj/project.pbxproj, package.json, src/hooks/useProfile.ts, src/screens/MyPageScreen/index.tsx, src/screens/OrderHistoryScreen/index.tsx, src/screens/RegisterScreen/LoginScreen.tsx, src/screens/SubscribeScreen/index.tsx, yarn.lock
close: #81
- zustand 설치
- useProfile 훅 추가
- 앱 초기 실행 시 실행 시킬 함수들을 관리하는 방법을 알아볼 필요가 있을 것 같네요.
- `setUpPushNotificationHandlers`
- profile refresh
=> feat: zustand 도입 및 `useProfile` 훅 작성합니다.

android/app/build.gradle
=> release: 0.0.1

src/apis/Login.ts, src/components/LoginPage/CredentialLogin.style.tsx, src/components/LoginPage/CredentialLogin.tsx, src/components/LoginPage/CredentialSignUp.tsx, src/navigation/HomeNavigator.tsx, src/navigation/RegisterNavigator.tsx, src/screens/RegisterScreen/LoginScreen.style.tsx, src/screens/RegisterScreen/LoginScreen.tsx, src/screens/RegisterScreen/SignupScreen.tsx
- close: #135 
- 일반 회원가입 및 로그인 페이지 제작
| 로그인 | 회원가입 |
| - | - |
| ![Screenshot_1737537664](https://github.com/user-attachments/assets/a6017279-194a-4289-875c-91e221007474) | ![Screenshot_1737538880](https://github.com/user-attachments/assets/2828e0ec-ead2-4236-a971-4d3ecae3159b) |
=> feat: 일반 회원 로그인 페이지 제작합니다.

src/apis/ApiClient.ts, src/apis/Bucket.ts, src/apis/Fcm.ts, src/apis/Login.ts, src/apis/Market.ts, src/apis/Order.ts, src/apis/Subscribe.ts
=> feat: api endpoint 마이그레이션

src/apis/buckets/client.ts, src/apis/buckets/index.ts, src/apis/buckets/model.ts, src/apis/buckets/query.ts, src/components/marketDetailPage/Menu.tsx, src/screens/MarketDetailScreen/MarketDetailPage.tsx, src/screens/PaymentScreen/index.tsx, src/screens/ShoppingCartScreen/ShoppingCartPage.tsx, src/screens/ShoppingCartScreen/index.tsx
- `buckets` entity react-query 마이그레이션합니다.
=> feat: react-query migration - buckets

src/apis/review/client.ts, src/apis/review/index.ts, src/apis/review/model.ts, src/apis/review/query.ts
- 리뷰 api 추가합니다.
- 다른 pr에서 ui 작업할게요
=> feat: review api 추가

.github/workflows/lint.yml
[참조](https://github.com/ummgoban/admin-client-app/pull/91)
작업 전에 확인하시면 머지 해주셔도 좋을 것 같아요!
=> ci: actions cache version up

src/apis/ApiClient.ts, src/apis/CustomError.ts, src/apis/auth/client.ts, src/apis/auth/query.ts, src/apis/buckets/client.ts, src/apis/markets/client.ts, src/apis/markets/query.ts, src/apis/orders/client.ts, src/apis/review/client.ts, src/components/LoginPage/CredentialLogin.tsx, src/hooks/useProfile.ts, src/screens/MyPageScreen/UserMyPage.tsx
- 에러 헨들링 코드 초안 작성합니다.
- 로그인 에러 `데이터베이스에서 사용자 정보를 찾을 수 없습니다.` 메시지를 View에서 Alert하는 예제 코드를 선제적으로 작성합니다.
| log | view |
| --- | ----- |
| <img width="510" alt="스크린샷 2025-03-05 오전 12 43 25" src="https://github.com/user-attachments/assets/2e667735-b2e6-411a-8dd5-e8096e21ba7b" /> | <img width="379" alt="스크린샷 2025-03-05 오전 12 43 36" src="https://github.com/user-attachments/assets/cd8c6310-7ccc-413b-845f-e4ef38cb5dfe" /> |
- 우선 동작하게는 했는데,, 더 깔끔하게는 고민해볼게요.
- `ApiClient` -> `<resource>/client.ts` -> `<resource>/query.ts` -> `view` 로 에러 객체를 계속 넘겨주는 것
- rect-query api 만으로 해결 가능한 지 이것이 안된다면 `Thenable`로 callback 을 해소 할 지, 고민입니다. 참고자료는 더 찾아봐야할 것 같네요.
- https://ko.javascript.info/custom-errors
=> feat: 에러헨들링 코드 작성합니다.

App.tsx, package.json, src/assets/icons/chevron-left.svg, src/components/LoginPage/CredentialLogin.style.tsx, src/components/LoginPage/CredentialLogin.tsx, src/components/LoginPage/CredentialSignUp.tsx, src/components/common/Appbar/AppbarOptions.ts, src/components/common/Appbar/AppbarOptions.tsx, src/components/common/TextInput/TextInput.style.tsx, src/components/common/TextInput/TextInput.tsx, src/components/feedPage/Market.tsx, src/context/index.tsx, src/navigation/CartNavigator.tsx, src/navigation/DetailNavigator.tsx, src/navigation/FeedNavigator.tsx, src/navigation/HomeNavigator.tsx, src/navigation/MyPageNavigator.tsx, src/navigation/RegisterNavigator.tsx, src/screens/FeedScreen/index.tsx, yarn.lock
=> feat: ios app bar, safe area, 인풋 디자인, validation

App.tsx, src/navigation/Layout.style.tsx, src/navigation/index.tsx
=> fix: change safearea to useSafeAreaInsets

src/apis/ApiClient.ts, src/apis/auth/client.ts, src/apis/auth/model.ts, src/apis/auth/query.ts, src/components/LoginPage/CredentialLogin.style.tsx, src/components/LoginPage/CredentialSignUp.tsx, src/components/common/TextInput/TextInput.tsx, src/hooks/useProfile.ts, src/screens/MarketDetailScreen/MarketDetail.style.tsx
- api call log 추가
- 이메일 인증 로직 추가
- 마켓 디테일 페이지 태그 다지인 수정
=> feat: 회원가입 이메일 인증 로직 구현

App.tsx, ios/Podfile.lock, src/components/common/BottomButton.style.tsx, src/components/common/EmptyComponent/EmptyComponent.style.tsx, src/components/common/ListBox.style.tsx, src/components/common/SubscribeIcon.tsx, src/components/common/TabBar.tsx, src/components/subscribePage/SubscribeMarketCard.style.tsx, src/navigation/CartNavigator.tsx, src/navigation/DetailNavigator.tsx, src/navigation/MyPageNavigator.tsx, src/navigation/index.tsx, src/screens/FeedScreen/Feed.style.tsx, src/screens/MarketDetailScreen/MarketDetail.style.tsx, src/screens/MyPageScreen/NoticePage.style.tsx, src/screens/MyPageScreen/UserMyPage.style.tsx, src/screens/OrderDoneScreen/OrderDoneScreen.style.tsx, src/screens/OrderDoneScreen/index.tsx, src/screens/OrderHistoryScreen/OrderHistory.style.tsx, src/screens/PaymentScreen/PaymentPage.style.tsx, src/screens/SettingScreen/SettingScreen.style.tsx, src/screens/ShoppingCartScreen/ShoppingCartPage.style.tsx, src/screens/SubscribeScreen/SubscribeScreen.style.tsx
- safeArea 적용
- safeArea 변경에 따라 페이지 디자인 white로 전체 변경 및 컴포넌트 디자인 변경
- 찜 쿼리키 갱신
|  |  |  |
| --- | --- | --- |
| ![Simulator Screenshot - iPhone 14 Pro Max - 2025-03-07 at 16 19 24](https://github.com/user-attachments/assets/be128698-5aee-415e-b0da-6573c0f1cf1c) | ![Simulator Screenshot - iPhone 14 Pro Max - 2025-03-07 at 16 19 31](https://github.com/user-attachments/assets/7b146ded-97fa-4dad-aba5-df630ea92049) | ![Simulator Screenshot - iPhone 14 Pro Max - 2025-03-07 at 16 19 42](https://github.com/user-attachments/assets/aa672072-fd84-4d86-95e8-84301944ba4e) |
| ![Simulator Screenshot - iPhone 14 Pro Max - 2025-03-07 at 16 19 45](https://github.com/user-attachments/assets/bec3ab6d-cf98-4145-91da-8c983e4974bf) | ![Simulator Screenshot - iPhone 14 Pro Max - 2025-03-07 at 16 19 …
=> fix: safeArea 적용 및 그에 따른 디자인 변경

src/components/common/TabBar.tsx, src/navigation/CartNavigator.tsx, src/navigation/DetailNavigator.tsx, src/screens/PaymentScreen/PaymentPage.tsx
=> feat: 주문 시 주문 목록 쿼리키 갱신

src/components/common/SubscribeIcon.tsx
=> feat: 찜 버튼 로그인 여부 체크

src/apis/auth/client.ts, src/apis/auth/query.ts, src/components/LoginPage/CredentialSignUp.tsx
- send-code api 변경
- 회원가입 피드백 추가
- 로딩서클
- 모달
https://github.com/user-attachments/assets/66eff972-1caa-402a-bb22-31469e284ddd
=> feat: email send api 수정 및 피드백 추가

src/apis/auth/query.ts, src/hooks/useProfile.ts, src/screens/MyPageScreen/UserMyPage.tsx
close: #168 
- 고객앱에서 useProfile에 zustand를 제거합니다.
- getProfile에서 에러를 던지면 profile을 null로 수정합니다.
=> feat: 로그아웃 후 프로필을 null로 세팅합니다.

src/apis/review/client.ts, src/apis/review/query.ts, src/components/orderHistory/OrderHistory.tsx, src/screens/ReviewScreen/index.tsx, src/types/StackNavigationType.ts, src/utils/notification.ts
=> fix: review api endpoint

src/components/marketReview/MarketReviewCard.style.tsx, src/components/marketReview/MarketReviewCard.tsx, src/components/marketReview/MarketReviewReplyCard.style.tsx, src/components/marketReview/MarketReviewReplyCard.tsx
resolves: #181
- 사장님 답글 컴포넌트 제작해서 페이지에 부착했습니다. 
<p>
</p>
=> feat: 사장님 리뷰 답글 컴포넌트 제작

src/apis/auth/oauthHelper.ts
- 애플 초기 로그인시에는 이름값이 있고 이후에는 null이어서 안보내기로 했습니다.
=> fix: apple-login-request

src/screens/CustomerReviewScreen/index.tsx
=> feat: 마이페이지의 나의 리뷰에서 리뷰가 없는 경우 페이지 제작합니다.

src/components/common/DatePicker.tsx, src/components/orderPage/DatePickerCard.style.tsx, src/components/orderPage/DatePickerCard.tsx, src/screens/MarketDetailScreen/MarketDetailPage.tsx, src/screens/PaymentScreen/PaymentPage.tsx
resolve: https://www.notion.so/4-28-1e3e86f38f4d806f9354d88215e775f0?pvs=4#1e3e86f38f4d8048b156e875026d4196
- 픽업 시간이 지난 경우 내일 픽업 가능 시간으로 예약합니다.
- 픽업 시간 기본값을 현재 시간에서 `min(픽업 가능 시작 시간, 현재 시간)`으로 로직을 수정합니다.
=> fix: 픽업 예약 시간 관련 로직 수정합니다.

src/components/feedPage/Market.tsx
- FlatList scrollEnabled 속성 이용하여 캐로셀 스크롤 제한
해당 이슈 해결했습니다.
https://github.com/user-attachments/assets/a2417d1f-41fe-4cd6-947f-57f4d64e164a
=> fix: 마켓 캐로셀 반찬 3개 이상부터 스크롤 허용

src/apis/ApiClient.ts, src/apis/CustomError.ts, src/apis/auth/client.ts, src/hooks/useProfile.ts, src/screens/RegisterScreen/LoginScreen.tsx, src/types/Session.ts, yarn.lock
=> fix: 유저 도메인 관련 버그 수정 및 고도화 작업합니다

.script/android-build.sh, android/app/build.gradle, android/build.gradle, package.json, yarn.lock
=> release: v1.1.0

src/apis/buckets/client.ts, src/screens/ShoppingCartScreen/ShoppingCartPage.tsx
장바구니 페이지 데이터를 서버와 동기화하였습니다.
https://github.com/user-attachments/assets/2507f810-f7a9-46d8-9021-b6ac0c40f41d
)
=> fix: 장바구니 페이지 서버와 동기화

src/components/orderDetail/OrderDescription.tsx
=> fix: 주문이 완료되지 않은 경우 완료 시간 미포함

.github/workflows/auto-release.yml
`release: v[x].[y].[z]`형식의 PR이 main으로 머지 시 tag와 release를 생성합니다.
=> chore: auto release workflow

src/apis/auth/oauthHelper.ts
기존 방식과 동일하게 네이버 앱 열려 로그인 하는 방식으로 변경했습니다.
=> fix: 네이버 로그인 앱 인증으로 변경
