ummgoban/client-app

src/navigation/DetailNavigator.tsx, src/screens/OrderDoneScreen/OrderDoneScreen.style.tsx, src/screens/OrderDoneScreen/index.tsx, src/screens/PaymentScreen/PaymentPage.tsx, src/types/StackNavigationType.ts
resolves: #11 
- 결제하기 페이지 간단히 구현합니다.
- 결제 완료 시 홈으로 돌아갈 수 있게합니다.
- `useNavigation` 사용하면 props drilling 없이 네비게이션할 수 있네요.
```
import {useNavigation} from '@react-navigation/native';
const navigation = useNavigation<StackNavigationProp<RootStackParamList>>();
```
| ![Screenshot_1727416443](https://github.com/user-attachments/assets/42d1ef39-ecc1-4a56-a880-22cd1998ebce) |
| - |
=> feat: create orderDoneScreen

src/apis/Login.ts, src/components/myPage/Profile.tsx, src/screens/MyPageScreen/index.tsx, src/screens/RegisterScreen/LoginScreen.tsx, src/types/Session.ts, src/types/Storage.ts, src/utils/storage.ts
resolves: #51
- 로그인 성공 시
- Home-Feed로 리디렉션합니다.
- 로그아웃 성공 시 
- `setStorage`를 호출하여 session을 빈 객체로 교체합니다.
- Home-Feed로 리디렉션합니다.
- `useIsFocused` 을 이용하여 마이페이지 접근 시 `getProfile`을 호출하도록 합니다.
- `type/**`하위의 Session과 Storage를 분리합니다.
`useIsFocused` 대신 리코일 등의 상태관리 라이브러리를 통해서 로그인 세션의 refresh를 컨트롤 하는 게 더 좋을 것 같지만, 일단은 임시 방편으로 이와 같이 구현합니다
=> feat: 로그인 및 로그아웃 후 리다이렉트, 리프레쉬 추가

src/screens/MarketDetailScreen/index.tsx
헤더에 가게이름 표시되도록 수정
```tsx
useEffect(() => {
navigation.setOptions({
title: marketDetail?.name ?? '가게 정보',
});
}, [marketDetail?.name, navigation]);
```
=> feat: 가게 이름을 헤더에 표시

android/app/src/main/AndroidManifest.xml, ios/Podfile.lock, package.json, src/context/TossPaymentProvider.tsx, src/context/index.tsx, src/screens/PaymentScreen/PaymentPage.tsx, yarn.lock
resolves: #45 
- 토스 페이먼츠 연결
- 토스 페이먼츠 sdk version2가 react native를 지원하지 않아 v1을 설치하여 사용합니다.
- 우리 앱에 맞는 스타일 적용 및 콜백 로직은 다음 pr에서 작업할게요
| andriod | ios |
| - | - |
| ![Screenshot_1730276332](https://github.com/user-attachments/assets/e1b97a81-a86d-4546-91bb-4444bbfbdf3b) |![Simulator Screenshot - iPhone SE (3rd generation) - 2024-10-30 at 17 46 20](https://github.com/user-attachments/assets/bf7e12a9-59c4-497f-9f82-4f074ae5c48e) |
=> chore: 토스 페이먼츠 세팅

.gitignore, src/apis/Login.ts, src/apis/Subscribe.ts, src/components/common/TabBar.tsx, src/components/subscribePage/SubscribeMarketCard.style.tsx, src/components/subscribePage/SubscribeMarketCard.tsx, src/navigation/HomeNavigator.tsx, src/screens/SubscribeScreen/SubscribeScreen.style.tsx, src/screens/SubscribeScreen/index.tsx, src/types/StackNavigationType.ts, src/types/Subscribe.ts
resloves: #37 
- 찜 가게 카드 컴포넌트 제작
- 찜 페이지 제작
- 바텀 탭바 페이지 순서 변경
```
type SubscribeType = {
id: number;
name: string;
address: string;
specificAddress: string;
openAt: string;
closeAt: string;
products: ProductType[];
};
```
안드로이드 이미지가 자꾸 깨지네요.. 빌드 확인했습니다.
가게 카드에서 찜한 가게 삭제 버튼 있으면 좋을듯 합니다.
api 이슈좀 해결되고 디자인 나오면 적용하겠습니다.
=> feat: 찜 가게 페이지 제작

src/apis/Bucket.ts, src/apis/Order.ts, src/components/marketDetailPage/Menu.style.tsx, src/components/marketDetailPage/Menu.tsx, src/components/orderPage/PaymentSummary.tsx, src/navigation/DetailNavigator.tsx, src/screens/MarketDetailScreen/MarketDetail.style.tsx, src/screens/MarketDetailScreen/MarketDetailPage.tsx, src/screens/MarketDetailScreen/index.tsx, src/screens/OrderDoneScreen/index.tsx, src/screens/PaymentScreen/PaymentPage.tsx, src/screens/ShoppingCart/ShoppingCartPage.tsx, src/types/Market.ts, src/types/ProductType.ts, src/types/StackNavigationType.ts
resolves: #79 
| iOS | Android |
| --- | --- |
| ![iOS Image](https://github.com/user-attachments/assets/254232c3-1d0a-42e7-83fb-58db7f9aec01) | ![Android Image](https://github.com/user-attachments/assets/250e1abc-f11d-4576-9890-fe3c9681829e) |
승민이형 MarketDetail 변수명 깔끔하게 하셨는데 디자인 제가 잘못해서 그런거 같습니다 망쳐놨네요..
차후 잘 고쳐보겠습니다...
=> fix: 가게 상세 페이지 디자인

src/components/common/TabBar.style.tsx, src/components/common/TabBar.tsx, src/components/orderHistory/OrderHistory.tsx
=> fix: 주문 내역 표시 및 바텀 아이콘 적용

src/components/feedPage/Market.tsx, src/components/map/MyLocationMap.tsx, src/components/orderPage/PaymentSummary.tsx, src/screens/FeedScreen/index.tsx, src/screens/MarketDetailScreen/MarketDetailPage.tsx, src/screens/MarketDetailScreen/index.tsx, src/screens/MyPageScreen/UserMyPage.tsx, src/types/Bucket.ts, src/types/ProductType.ts
=> feat: 마켓 표시 로직 추가

android/app/src/main/AndroidManifest.xml, android/app/src/main/java/com/clientapp/MainActivity.kt, ios/ClientApp.xcodeproj/project.pbxproj, src/apis/Fcm.ts, src/screens/FeedScreen/index.tsx, src/utils/notification.ts
- fcm android 헤드업 알림 추가
- fcm 앱 어드민 유저 병합
- fcm notifee 라이브러리 추가 
어드민 로직 그대로 가져왔습니다.
fcm 설정변경으로 인해 파일 변경하셔야합니다.
슬랙에 업로드 해놓겠습니다.
=> fix: fcm android headup 알림 추가, fcm 어드민 유저 병합

src/apis/Login.ts, src/apis/User.ts, src/components/common/SettingsNavigatorIcon.tsx, src/navigation/MyPageNavigator.tsx, src/navigation/index.tsx, src/screens/FeedScreen/SearchBar.style.tsx, src/screens/FeedScreen/index.tsx, src/screens/MyPageScreen/UserMyPage.tsx, src/screens/MyPageScreen/index.tsx, src/screens/SettingScreen/SettingScreen.style.tsx, src/screens/SettingScreen/index.tsx, src/types/StackNavigationType.ts, src/types/UserType.ts, src/utils/common.ts
- #88
- 세팅 페이지 뷰 구현합니다.
- 위치 기반 알림 등록과 알림 설정 등록 로직 여기로 옮겨야합니다.
| ![Screenshot_1732534507](https://github.com/user-attachments/assets/5861dffb-fb02-410d-9174-7611071fdee5) |
| - |
=> feat: setting 페이지 구성합니다. (뷰)

src/screens/MarketDetailScreen/MarketDetailPage.tsx
- 페이지 리로드될때마다 프론트 cart상태만 0으로 처리(직전 handleCheckout에서 이미 서버에 담은 cart를 넘겨서 상관없음)
- 장바구니 비어있을시 네비게이트 막고 Alert 띄웁니다
- count 항상 0으로 처리하는게 맞나 싶은데 내일 얘기해보죠 일단 얘기한대로 반영했습니다
=> fix: 가게 상세 페이지 조회시 항상 count 0 처리, 장바구니 비어있을시 이동 제어

src/apis/Login.ts, src/types/UserType.ts
- getProfile api 적용했습니다.
- 프로필 이미지 백엔드에서 저장 안하고있다고 해서 일단 옵셔널로 고치고 TODO에 기입했습니다.
=> fix: getProfile api 로직으로 변경

src/components/orderDetail/OrderDescription.tsx, src/screens/OrderDoneScreen/index.tsx, src/types/StackNavigationType.ts, src/utils/hash.ts
- hash function 사용해서 뷰 단에서만 주문번호 유지하도록 했습니다.
- 어드민에서도 동일 함수 적용시 클라 == 어드민 확인했습니다.
| ![Image 1](https://github.com/user-attachments/assets/adff2eaa-90ae-4558-91c1-9849f3a9e873) | ![Image 2](https://github.com/user-attachments/assets/69e83db2-8289-4fed-8912-6443094c0b36) |
|:--:|:--:|
동일 함수 적용해서 어드민에서 피알 올리겠습니다.
=> fix: orderId 6자리 해쉬값으로 변경

App.tsx, src/apis/Login.ts, src/screens/FeedScreen/index.tsx, src/screens/SettingScreen/index.tsx, src/utils/notification.ts
초기 화면 진입 잘 합니다.
아까 논의 나눴던 로직 거의 다 고친 것 같은데,
제일 초기 상황(기기 새로 만든 상황)에서 소셜로그인 시 네이버/카카오 정보가 저장안되어있어서 앱이 메트로랑 끊겨
테스트가 힘든 듯 합니다.. 빌드 터져서 실기기 못해보고 올립니다.
내일 상민이형이랑 오전에 서버로그 보면서 수정하겠습니다.
=> fix: fcm 로직 및 스플래시 스크린 초기 해결

android/app/src/main/AndroidManifest.xml, ios/ClientApp/Info.plist, ios/ClientApp/PrivacyInfo.xcprivacy, ios/Podfile.lock, package.json, src/components/common/TextInput/TextInput.tsx, src/components/orderHistory/OrderHistory.style.tsx, src/components/orderHistory/OrderHistory.tsx, src/components/review/RaitingStarts.style.tsx, src/components/review/RatingStarts.tsx, src/components/review/UploadedPicture.style.tsx, src/components/review/UplodedPicture.tsx, src/navigation/DetailNavigator.tsx, src/screens/ReviewScreen/ReviewScreen.style.tsx, src/screens/ReviewScreen/index.tsx, src/types/OrderType.ts, src/types/StackNavigationType.ts, src/utils/image-picker.ts, yarn.lock
resolves: #136 
- react-native-image-picker 설치 및 사용(사장앱과 동일)
- 별점 컴포넌트 구현
- 사진 업로드 컴포넌트 구현
- 리뷰 페이지 제작
- 주문 상세 페이지에서 navigate
<p align="center">
</p>
주문 목록에서 /customer/orders respons에 `review: boolean` 타입 추가
review: false && 주문이 종료되었을 때(orderStatus === PICKED_UP) 시 리뷰 작성 버튼 조건부 렌더링 
리뷰 작성하기 버튼은 TextInput 박스 입력 string만 가지고 disabled 걸었습니다.
TextInput 컴포넌트 height를 억지로 늘렸다가 다시 줄였습니다.
외부에서 주입할 수 있는 방법이 현재 있나요..?
- 고객 본인이 작성한 리뷰 조회 페이지
- 고객 리뷰 수정 기능
- 고객 리뷰 작성 중 s3 업로드 image 삭제(api 필요)
- 사장님 리뷰 조회 페이지 디자인 수정
<p >
</p>
=> feat: 고객 리뷰 페이지 구현

src/apis/review/client.ts, src/apis/review/model.ts, src/apis/review/query.ts, src/components/common/ListBox.tsx, src/components/common/NavigateTextButton.tsx, src/components/common/customerReview/CustomerReviewCard.style.tsx, src/components/common/customerReview/CustomerReviewCard.tsx, src/components/common/customerReview/index.ts, src/navigation/DetailNavigator.tsx, src/navigation/MyPageNavigator.tsx, src/screens/CustomerReviewScreen/CustomerReviewScreen.style.tsx, src/screens/CustomerReviewScreen/index.tsx, src/screens/MyPageScreen/UserMyPage.tsx, src/types/Review.ts, src/types/StackNavigationType.ts
- 고객 본인의 리뷰 조회 페이지 
- 마이페이지 내에서 리다이렉트 버튼 추가
<div>
</div>
https://github.com/user-attachments/assets/5499cd27-3acd-48e3-ba77-b48055ae30f0
가게 내 리뷰 조회랑 흡사해 파일 하나로 맞춰보려 했으나 리스폰스가 살짝 달라 파일 분리했습니다.
- 자신 말고 타인까지 리뷰 조회까지 바로 가능한데 추가할까요?
- 리뷰 조회를 바텀 네비바에 넣는게 나았으려나요?
배민 카피하려고 마이페이지에 억지로 우겨넣은 느낌이 없지 않습니다.
바텀 네비바는 디자인도 해주신거라 손대기 좀 그렇네요..
=> feat: 고객 자신 리뷰 조회 기능 추가

src/components/feedPage/Market.style.tsx, src/components/feedPage/Market.tsx
- feed page 캐로셀 스크롤 정상화
https://github.com/user-attachments/assets/b96d60b3-6299-48e9-a9c0-f91191c9a7bb
안드로이드도 확인했습니다!
기존 TouchableOpacity + map 조합에서 Pressable + FlatList로 변경했습니다.
Pressable에서 드래그를 감지하는 순간 FlatList로 터치 제어권이 넘어가 스크롤이 가능합니다.
대신 기존 TouchableOpacity에서 기본으로 유지되던 터치할 때 opacity 적용은 없어졌습니다..
적용해보려 시도해보다 배민도 터치 이벤트가 따로 없어 pr 작성합니다. TODO로 남겨놓겠습니다.
=> fix: 캐로셀 스크롤 정상화

src/navigation/CartNavigator.tsx, src/navigation/DetailNavigator.tsx, src/navigation/FeedNavigator.tsx, src/navigation/HomeNavigator.tsx, src/navigation/MyPageNavigator.tsx, src/navigation/RegisterNavigator.tsx
- iOS 백버튼 color 주입
<p >
</p>
navigatorOption을 상단에 선언하는게 나을까요?
commonScreenOption 선언 이후 페이지에서 덮어쓰는 형식으로 변경해봤습니다.
기존 방식이 나으면 원복하겠습니다~!
lint warning이 발생했었네요.. 이전에도 그래서 지금 형식으로 변경했던 것 같습니다.
common을 선언하고, 상단에서 option을 선언 이후 각 페이지에 주입했습니다.
어프루브 눌러주시면 어드민도 진행할게요!
rn 뭔가 감싸진게 많네요 속성을 잘 넣어주면 잘되네요
=> fix: iOS back button color 주입

src/components/LoginPage/CredentialLogin.tsx, src/components/common/ActivityIndicator.style.tsx, src/screens/MarketDetailScreen/MarketDetailPage.tsx, src/screens/MyPageScreen/NicknamePatchPage.tsx, src/screens/MyPageScreen/UserMyPage.tsx, src/screens/PaymentScreen/PaymentPage.tsx, src/screens/RegisterScreen/LoginScreen.tsx, src/screens/ReviewCreateScreen/index.tsx
resolves: #225 
- api pending 시 스크린에 반영
-   중복 전송의 side-effect가 큰 api와 및 상태 변경 api 위주로 진행
- 사장님 요구사항 중 credential 로그인 id placeholder 아이디 -> 이메일로 변경
https://github.com/user-attachments/assets/2e6cf71e-7e91-4c16-ad12-1699d3236f92
https://github.com/user-attachments/assets/6b394dc2-68f6-4ce1-bd85-e051e0c78e76
https://github.com/user-attachments/assets/47412e88-da97-41d7-b2cf-7bf5e35f47c3
기존 CustomActivityIndicator를 오버레이 형식으로 변경하여 적용했습니다.
커밋 메시지 별 스크린에 동일 로직 적용했습니다.
MutateAsync로 useMutation 사용하고 있는 스크린은 부득이하게 useState로 상태 하나 더 관리하여
async 함수 내부에서 상태 관리하였습니다.
=> fix: api pending 스크린 반영을 통한 ux 개선 및 중복 전송 방지

android/app/build.gradle, android/app/src/main/AndroidManifest.xml, src/modules/imagePicker/hook/use-image-picker.reducer.ts, src/modules/imagePicker/hook/use-image-picker.ts, src/modules/imagePicker/index.ts, src/modules/imagePicker/lib/image-picker.error.ts, src/modules/imagePicker/lib/image-picker.ts, src/navigation/DetailNavigator.tsx, src/screens/ReviewCreateScreen/index.tsx
- utils/ 하위에는 순수함수만을 유지하고 외부 라이브러리를 래핑하는 모듈의 경우는 modules로 분리하는 구조로 제안합니다.
- utils/notification 등도 이와 같이 분리하면 좋겠습니다.
이미지 피커 사용시 사용자가 이미지를 선택하지 않고 종료하는 경우에도 에러를 던져 Alert 창이 나오는 것을 방지하기 위한 작업을 진행하였습니다.
- lib/ 
- 외부 라이브러리를 래핑하는 기능함수 파일
- type, error, const, enum 등의 상수와 타입선언 파일
- hook
- 클라이언트에서 사용할 react 훅.
- React hook, RN 내장 기능 등 클라이언트에서 사용하는 코드 사용
- 외부 노출
- index.ts
- 외부에 노출할 파일 선언
- `{}`를 활용하여 이름 강제하는 것이 좋은 것 같습니다. `export {useImagePicker} from './hook/use-image-picker';` 형식
- 필요시 lib/ 하위의 타입, 상수를 노출할 수도 있지만 hook에서 lib하위의 파일들은 모두 사용하고 클라이언트는 항상 hook에서 제공하는 함수와 변수만을 사용하는 구조면 좋을 것 같습니다.
- \*  react hook을 사용할 필요가 없는 경우에는 어떤 모듈을 export하도록 설계할지 파일 구조에 대해서 고민을 해볼게요.
해당 AndroidManifest.xml 설정에서 dev 실행은 되는데 release 빌드가 안되는 에러가 있습니다... 혹시 한번 같이 찾아주시면 압도적 감사
```xml
<service …
```
=> refactor: image-picker 모듈 분리
